/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import logica.Cliente;
import logica.Mensaje;
import logica.Servidor;

import java.io.File;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.text.html.HTML;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 * @author tona
 */
public class Chat extends javax.swing.JFrame {
    private static Element body = null;
    private StyleSheet styleSheet;
    private static HTMLDocument doc;
    private File imagen;
    private Servidor s;
    private Cliente c;
    private String nickname;
    private static DefaultListModel modelo;

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
        modelo = new DefaultListModel();
        listUsuarios.setModel(modelo);
        obtenerBody();
        crearSocket();
    }

    public Chat(String nickname) {
        this();
        this.nickname = nickname;
        c.enviarAnuncio(this.nickname);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelMensajes = new javax.swing.JEditorPane();
        btnCargar = new javax.swing.JButton();
        btnCaquita = new javax.swing.JButton();
        btnFeliz = new javax.swing.JButton();
        btnEnojado = new javax.swing.JButton();
        btnCorazon = new javax.swing.JButton();
        btnTriste = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaMensaje = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Chat Grupal");
        setResizable(false);

        jLabel1.setText("Super chat grupal");

        panelMensajes.setEditable(false);
        panelMensajes.setContentType("text/html"); // NOI18N
        panelMensajes.setEditorKit(new HTMLEditorKit());
        panelMensajes.setText("<!DOCTYPE html>\n<html>\n  <head>\n\n  </head>\n  <body></body>\n</html>\n");
        panelMensajes.setAutoscrolls(false);
        jScrollPane2.setViewportView(panelMensajes);

        btnCargar.setText("Cargar Imagen");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnCaquita.setText("<:3");
        btnCaquita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaquitaActionPerformed(evt);
            }
        });

        btnFeliz.setText("=)");
        btnFeliz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFelizActionPerformed(evt);
            }
        });

        btnEnojado.setText(">=|");
        btnEnojado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnojadoActionPerformed(evt);
            }
        });

        btnCorazon.setText("<3");
        btnCorazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorazonActionPerformed(evt);
            }
        });

        btnTriste.setText("='(");
        btnTriste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTristeActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtAreaMensaje.setColumns(10);
        txtAreaMensaje.setLineWrap(true);
        txtAreaMensaje.setRows(5);
        txtAreaMensaje.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtAreaMensaje);

        jLabel2.setText("Usuarios conectados");

        jLabel3.setText("Escribe un mensaje");

        btnVolver.setText("Volver al chat grupal");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCaquita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFeliz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnojado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCorazon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTriste)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(btnCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btnEnviar))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnTriste)
                    .addComponent(btnCorazon)
                    .addComponent(btnEnojado)
                    .addComponent(btnFeliz)
                    .addComponent(btnCaquita))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecciona una imagen a enviar");
        if (jfc.showDialog(this, "Seleccionar") == JFileChooser.APPROVE_OPTION) {
            imagen = jfc.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Imagen lista para enviar");
            btnCargar.setText("Imagen en espera");
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCorazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorazonActionPerformed
        // TODO add your handling code here:
        agregarEmoji(obtenerMensaje() + " <3 ");
    }//GEN-LAST:event_btnCorazonActionPerformed

    private void btnCaquitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaquitaActionPerformed
        // TODO add your handling code here:
        agregarEmoji(obtenerMensaje() + " :poop: ");
    }//GEN-LAST:event_btnCaquitaActionPerformed

//GEN-FIRST:event_btnFelizActionPerformed
    private void btnFelizActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        agregarEmoji(obtenerMensaje() + " =) ");
    }//GEN-LAST:event_btnFelizActionPerformed

//GEN-FIRST:event_btnEnojadoActionPerformed
    private void btnEnojadoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        agregarEmoji(obtenerMensaje() + " >=| ");
    }//GEN-LAST:event_btnEnojadoActionPerformed

//GEN-FIRST:event_btnTristeActionPerformed
    private void btnTristeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        agregarEmoji(obtenerMensaje() + " ='( ");
    }//GEN-LAST:event_btnTristeActionPerformed

//GEN-FIRST:event_btnEnviarActionPerformed
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // TODO add your handling code here:
            Mensaje msj = new Mensaje();
            msj.setUsuario(this.nickname);
            if (imagen != null) {
                msj.setImagen(imagen.getAbsolutePath());
                msj.setTipoMensaje(Mensaje.IMAGEN);
                btnCargar.setText("Cargar Imagen");
                imagen = null;
            }
            msj.setMensaje(obtenerMensaje());
            txtAreaMensaje.setText("");
            c.enviarMensaje(msj);
        } catch (IOException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
        feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Chat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaquita;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCorazon;
    private javax.swing.JButton btnEnojado;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnFeliz;
    private javax.swing.JButton btnTriste;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JList<String> listUsuarios;
    private javax.swing.JEditorPane panelMensajes;
    private javax.swing.JTextArea txtAreaMensaje;
    // End of variables declaration//GEN-END:variables

    private String obtenerMensaje() {
        return txtAreaMensaje.getText();
    }

    private void obtenerBody() {
        styleSheet = new StyleSheet();
        HTMLEditorKit kit = (HTMLEditorKit) panelMensajes.getEditorKit();
        styleSheet.addRule("div {max-width:295px; word-wrap:break-word; overflow: hidden; width:295px;}");
        kit.setStyleSheet(styleSheet);
        panelMensajes.setEditorKit(kit);
        doc = (HTMLDocument) kit.createDefaultDocument();
        panelMensajes.setDocument(doc);
        Element[] roots = doc.getRootElements();

        for (int i = 0; i < roots[0].getElementCount(); i++) {
            Element element = roots[0].getElement(i);
            System.out.println(element.getAttributes().getAttribute(StyleConstants.NameAttribute));
            if (element.getAttributes().getAttribute(StyleConstants.NameAttribute) == HTML.Tag.BODY) {
                body = element;
                break;
            }
        }
    }

    private void crearSocket() {
        String dir="235.1.1.1";
        int puerto = 4445;
        try {
            InetAddress grupo = InetAddress.getByName(dir);
            MulticastSocket multicastSocket = new MulticastSocket(puerto);
            multicastSocket.joinGroup(grupo);
            multicastSocket.setTimeToLive(255);
            multicastSocket.setReuseAddress(true);

            s = new Servidor(multicastSocket);
            c = new Cliente(multicastSocket, grupo);

            new Thread(s).start();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void agregarMensaje(Mensaje msj) throws IOException, BadLocationException {
        doc.insertBeforeEnd(body, msj.construirMensaje());
    }

    private void agregarEmoji(String msj) {
        txtAreaMensaje.setText(msj);
    }

    public static void agregarUsuarioLista(String usuario) {
        modelo.addElement(usuario);
    }
}
